path: C:\Users\jaysu\OneDrive\Desktop\Nexsync project\yolos\dataset # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Classes
nc: 2
names: ['pothole', 'speedbump']